# Generated by Django 5.2.1 on 2025-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonExclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('article_color_name', models.CharField(max_length=100)),
                ('master_season', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('dept_div', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subclass', models.CharField(max_length=100)),
                ('style_number', models.CharField(max_length=50)),
                ('style_desc', models.CharField(max_length=255)),
                ('color_desc', models.CharField(max_length=100)),
                ('size_desc', models.CharField(max_length=20)),
                ('multipack_qty', models.IntegerField()),
                ('variant_number', models.CharField(max_length=50)),
                ('upc', models.CharField(max_length=20)),
                ('asin', models.CharField(max_length=20)),
                ('current_status', models.CharField(max_length=50)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planned_discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('planned_asp', models.DecimalField(decimal_places=4, max_digits=10)),
                ('merch_like_styles', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
