# Generated by Django 5.2.1 on 2025-06-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazoneMapApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonexclusive',
            name='article_color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='asin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='color_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='current_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='dept_div',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='master_season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='multipack_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='planned_asp',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='planned_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='size_desc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='style_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='style_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='subclass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='upc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='variant_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
