# Generated by Django 5.2.1 on 2025-06-11 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazoneMapApp', '0002_alter_amazonexclusive_article_color_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonexclusive',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazonexclusives_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amazonexclusive',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazonexclusives_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
