# Generated by Django 5.2.1 on 2025-06-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazoneMapApp', '0003_amazonexclusive_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonexclusive',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='planned_asp',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='amazonexclusive',
            name='planned_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=40),
        ),
    ]
